// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pb/interfaces.proto

package interfaces

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on Interface with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Interface) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Name

	if _, ok := _Interface_Status_NotInLookup[m.GetStatus()]; ok {
		return InterfaceValidationError{
			field:  "Status",
			reason: "value must not be in list [0]",
		}
	}

	if _, ok := Interface_Status_name[int32(m.GetStatus())]; !ok {
		return InterfaceValidationError{
			field:  "Status",
			reason: "value must be one of the defined enum values",
		}
	}

	for idx, item := range m.GetAddresses() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return InterfaceValidationError{
					field:  fmt.Sprintf("Addresses[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// InterfaceValidationError is the validation error returned by
// Interface.Validate if the designated constraints aren't met.
type InterfaceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InterfaceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InterfaceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InterfaceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InterfaceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InterfaceValidationError) ErrorName() string { return "InterfaceValidationError" }

// Error satisfies the builtin error interface
func (e InterfaceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInterface.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InterfaceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InterfaceValidationError{}

var _Interface_Status_NotInLookup = map[Interface_Status]struct{}{
	0: {},
}

// Validate checks the field values on IpAddress with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *IPAddress) Validate() error {
	if m == nil {
		return nil
	}

	switch m.Address.(type) {

	case *IpAddress_Ipv4:

		if ip := net.ParseIP(m.GetIpv4()); ip == nil || ip.To4() == nil {
			return IpAddressValidationError{
				field:  "Ipv4",
				reason: "value must be a valid IPv4 address",
			}
		}

	case *IpAddress_Ipv6:

		if ip := net.ParseIP(m.GetIpv6()); ip == nil || ip.To4() != nil {
			return IpAddressValidationError{
				field:  "Ipv6",
				reason: "value must be a valid IPv6 address",
			}
		}

	}

	return nil
}

// IpAddressValidationError is the validation error returned by
// IpAddress.Validate if the designated constraints aren't met.
type IpAddressValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IpAddressValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IpAddressValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IpAddressValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IpAddressValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IpAddressValidationError) ErrorName() string { return "IpAddressValidationError" }

// Error satisfies the builtin error interface
func (e IpAddressValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIpAddress.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IpAddressValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IpAddressValidationError{}
